production:
  adapter: postgresql
  database: "openlayer_prd"
  host: localhost
  username:
  password:
  encoding: utf8

development:
  adapter: postgresql
  database: "openlayer_dev"
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8

test:
  adapter: postgresql
  database: "openlayer_tst"
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8
